config/routes.rb
ContratosAragon::Application.routes.draw do
  resources :contracts

  match '/Contracts/BusquedaPorProcedimiento', :to => 'contracts#searchByProcedure'
  match '/Contracts/BusquedaPorEmpresa', :to => 'contracts#searchByCompanyName'
  match '/Contracts/BusquedaPorOrganismo', :to => 'contracts#searchByDepartment'
  match '/Contracts/BusquedaPorContratante', :to => 'contracts#searchBySignedBy'
  
  root :to => "contracts#index"

end

app/models/contract.rb
class Contract < ActiveRecord::Base
  cattr_reader :per_page
  @@per_page = 50
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

  caches_action :index, :cache_path => Proc.new { |c| c.params },  :expires_in => 10.minute
  caches_action :show, :cache_path => Proc.new { |c| c.params },  :expires_in => 10.minute
  caches_action :searchByProcedure, :cache_path => Proc.new { |c| c.params } ,  :expires_in => 10.minute
  caches_action :searchByCompanyName, :cache_path => Proc.new { |c| c.params },  :expires_in => 10.minute
  caches_action :searchByDepartment, :cache_path => Proc.new { |c| c.params },  :expires_in => 10.minute
  caches_action :searchBySignedBy, :cache_path => Proc.new { |c| c.params },  :expires_in => 10.minute
  

  # GET /contracts
  # GET /contracts.xml
  def index
    @contractsAllCount = Contract.all.size #check if we should do this for performance reasons
    @contracts = Contract.paginate :page => params[:page], :per_page => 50
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contracts }
    end
  end

  # GET /contracts/1
  # GET /contracts/1.xml
  def show
    @contract = Contract.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contract }
    end
  end
  
  # Search by procedure
  def searchByProcedure
     @contracts = Contract.find :all, :conditions => [ " procedure like ? ", "%" + params[:procedimiento ] + "%"]
     @contractsAllCount = @contracts.size #check if we should do this for performance reasons
     @contracts = @contracts.paginate :page => params[:page], :per_page => 50
     respond_to do |format|
       format.html { render :template => "contracts/index.html.erb" }
       #format.html contracts/index.html.erb
       format.xml  { render :xml => @contracts }
     end
   end
  
   def searchByCompanyName
      @contracts = Contract.find :all, :conditions => [ " company_name like ? ", "%"+ params[:empresa ] + "%"]
      @contractsAllCount = @contracts.size #check if we should do this for performance reasons
      @contracts = @contracts.paginate :page => params[:page], :per_page => 50
      respond_to do |format|
        format.html { render :template => "contracts/index.html.erb" }
        #format.html contracts/index.html.erb
        format.xml  { render :xml => @contracts }
      end
    end
    
    def searchByDepartment
        @contracts = Contract.find :all, :conditions => [ " department like ? ", "%"+ params[:organismo ] + "%"]
        @contractsAllCount = @contracts.size #check if we should do this for performance reasons
        @contracts = @contracts.paginate :page => params[:page], :per_page => 50
        respond_to do |format|
          format.html { render :template => "contracts/index.html.erb" }
          #format.html contracts/index.html.erb
          format.xml  { render :xml => @contracts }
        end
    end
    
    def searchBySignedBy
        @contracts = Contract.find :all, :conditions => [ " signed_by like ? ", "%"+ params[:contratante ] + "%"]
        @contractsAllCount = @contracts.size #check if we should do this for performance reasons
        @contracts = @contracts.paginate :page => params[:page], :per_page => 50
        respond_to do |format|
          format.html { render :template => "contracts/index.html.erb" }
          #format.html contracts/index.html.erb
          format.xml  { render :xml => @contracts }
        end
    end
=begin
  # GET /contracts/new
  # GET /contracts/new.xml
  def new
    @contract = Contract.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contract }
    end
  end

  # GET /contracts/1/edit
  def edit
    @contract = Contract.find(params[:id])
  end

  # POST /contracts
  # POST /contracts.xml
  def create
    @contract = Contract.new(params[:contract])

    respond_to do |format|
      if @contract.save
        format.html { redirect_to(@contract, :notice => 'Contract was successfully created.') }
        format.xml  { render :xml => @contract, :status => :created, :location => @contract }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contract.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contracts/1
  # PUT /contracts/1.xml
  def update
    @contract = Contract.find(params[:id])

    respond_to do |format|
      if @contract.update_attributes(params[:contract])
        format.html { redirect_to(@contract, :notice => 'Contract was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contract.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.xml
  def destroy
    @contract = Contract.find(params[:id])
    @contract.destroy

    respond_to do |format|
      format.html { redirect_to(contracts_url) }
      format.xml  { head :ok }
    end
  end
=end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= form_for(@contract) do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :contract_type %><br />
    <%= f.text_field :contract_type %>
  </div>
  <div class="field">
    <%= f.label :procedure %><br />
    <%= f.text_field :procedure %>
  </div>
  <div class="field">
    <%= f.label :budget_announced %><br />
    <%= f.text_field :budget_announced %>
  </div>
  <div class="field">
    <%= f.label :budget_adjudicated %><br />
    <%= f.text_field :budget_adjudicated %>
  </div>
  <div class="field">
    <%= f.label :idweb %><br />
    <%= f.text_field :idweb %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :signed_by %><br />
    <%= f.text_field :signed_by %>
  </div>
  <div class="field">
    <%= f.label :resolution_date %><br />
    <%= f.text_field :resolution_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<%= will_paginate @contracts %>
<%= @contractsAllCount %> contratos encontrados

<table>
  <tr>
    <th>Título</th>
	<!--
    <th>Description</th>
	-->
    <th>Tipo contrato</th>
    <th>Proc.</th>
	<!--
    <th>Budget announced</th>
	-->
    <th>EUR</th>
    <th>Contrante</th>
    <th>Empresa</th>
    <th>Organismo</th>
	<!--
    <th>Signed by</th>
	-->
    <th>Fecha res.</th>
	<th>Original doc</th>
	<!--
    <th></th>
    <th></th>
    <th></th>
	-->
  </tr>

<% @contracts.each do |contract| %>
  
 <tr class="<%=cycle('odd','even') %>">
    <td><%= link_to contract.title, contract %></td>
	<!--
    <td><%= contract.description %></td>
	-->
    <td><%= contract.contract_type %></td>
    <td>
		<!-- para cambiar por link_to-->
		<a href="/Contracts/BusquedaPorProcedimiento?procedimiento=<%= contract.procedure %>">
			<%= contract.procedure %>
		</a>
	</td>
    <td><%= contract.budget_announced %></td>
	<!--
    <td><%= contract.idweb %></td>
	-->
	<td>
		<a href="/Contracts/BusquedaPorContratante?contratante=<%= contract.signed_by %>">
			<%= contract.signed_by %>
		</a>
	</td>
    <td>
		<!-- para cambiar por link_to-->
		<a href="/Contracts/BusquedaPorEmpresa?empresa=<%= contract.company_name %>">
			<%= contract.company_name %>
		</a>
	</td>
    <td>
		<a href="/Contracts/BusquedaPorOrganismo?organismo=<%= contract.department %>">
			<%= contract.department %>
		</a>
    </td>
	<!--
    <td><%= contract.signed_by %></td>
	-->
    <td><%= contract.resolution_date %></td>
	<td>
		<a href="https://servicios.aragon.es/pcon/pcon-public/controlAdjudicacionPublico?accion=ACCION_SELECCIONAR_ADJUDICACION_PUBLICO&iddatoadjudicacion=<%=contract.idweb%>">
		<%= contract.idweb %></a>
	</td>
	<!--
    <td><%= link_to 'Show', contract %></td>
    <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
    <td><%= link_to 'Destroy', contract, :confirm => 'Are you sure?', :method => :delete %></td>
	-->
  </tr>
<% end %>
</table>

<br />

<!--
<%= link_to 'New Contract', new_contract_path %>
-->

app/views/contracts/new.html.erb
<h1>New contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @contract.title %>
</p>

<p>
  <b>Description:</b>
  <%= @contract.description %>
</p>

<p>
  <b>Contract type:</b>
  <%= @contract.contract_type %>
</p>

<p>
  <b>Procedure:</b>
  <%= @contract.procedure %>
</p>

<p>
  <b>Budget announced:</b>
  <%= @contract.budget_announced %>
</p>

<p>
  <b>Budget adjudicated:</b>
  <%= @contract.budget_adjudicated %>
</p>

<p>
  <b>Idweb:</b>
  <%= @contract.idweb %>
</p>

<p>
  <b>Company name:</b>
  <%= @contract.company_name %>
</p>

<p>
  <b>Department:</b>
  <%= @contract.department %>
</p>

<p>
  <b>Signed by:</b>
  <%= @contract.signed_by %>
</p>

<p>
  <b>Resolution date:</b>
  <%= @contract.resolution_date %>
</p>

<%= link_to 'Back', contracts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contratos públicos en Aragón</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>

  <div id="container">
    <header>
		<h1><a href="/">Contratos públicos en Aragón</a></h1>
    </header>

	    <div id="main" role="main">
		<div id=search>
			<form action="/Contracts/BusquedaPorEmpresa" method="get">
				<input name="empresa" type="text" size="50" value="<%=params[:empresa]%>">
				<input type=submit value="buscar por empresa">
			</form>
			<form action="/Contracts/BusquedaPorOrganismo" method="get">
				<input name="organismo" type="text" size="50" value="<%=params[:organismo]%>">
				<input type=submit value="buscar por organismo">
			</form>
		</div>
			<%= yield %>	
	    </div>
    <footer>
		<small>Powered by: RubyAndBeersZGZ</small>
    </footer>
  </div> <!--! end of #container -->
  


</body>
</html>